name: 'Build Image and Modernize UI'

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

defaults:
  run:
    shell: pwsh

jobs:
  build-image:
    name: 'Modernize and Build UI'

    strategy:
      matrix:
        system:
          - windows-2022

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone Dependencies
        run: |
          git clone --depth 1 https://github.com/hexalang/Hexa.git ../Hexa
          git clone --depth 1 https://github.com/GreenteaOS/Teapot.git ../Teapot
          git clone --depth 1 https://github.com/GreenteaOS/Tongue.git ../Tongue
          git clone --depth 1 https://github.com/GreenteaOS/NjRAA.git ../NjRAA

      - name: Modernize UI
        run: |
          # Navigate to the Assets directory
          cd ./Assets

          # Define intelligent changes
          $changes = @(
            @{ Pattern = '<button class="btn">'; Replacement = '<button class="btn btn-primary">' }, # Add primary class to buttons
            @{ Pattern = '<img '; Replacement = '<img alt="Image description" ' },                  # Add alt attributes to images
            @{ Pattern = 'font-family: Arial'; Replacement = 'font-family: Roboto, sans-serif' },    # Modern font family
            @{ Pattern = 'color: #000'; Replacement = 'color: #333' },                               # Better contrast
            @{ Pattern = '<h1>'; Replacement = '<h1 class="main-heading">' },                        # Add class to headings
            @{ Pattern = '<footer>'; Replacement = '<footer role="contentinfo">' },                 # Accessibility roles
            @{ Pattern = '<nav>'; Replacement = '<nav aria-label="Main navigation">' },             # Add ARIA labels
            @{ Pattern = 'onclick="handleClick()'; Replacement = 'onclick="modernHandleClick()"' },  # Update JS function name
            @{ Pattern = 'position: absolute'; Replacement = 'position: relative' },                # Modernize layout
            @{ Pattern = 'border: 1px solid #ccc'; Replacement = 'border: 2px solid #ccc' }         # Adjust border styles
          )

          # Apply changes to all relevant files in the Assets directory
          Get-ChildItem -Recurse -File -Filter '*.html', '*.css', '*.js' | ForEach-Object {
            $filePath = $_.FullName
            $content = Get-Content $filePath -Raw

            # Apply each change
            foreach ($change in $changes) {
              $content = $content -replace $change.Pattern, $change.Replacement
            }

            # Save updated content back to the file
            Set-Content -Path $filePath -Value $content
            Write-Host "Modernized file: $filePath"
          }

          Write-Host "UI modernization complete."

      - name: Build UI
        run: |
          # Navigate to Assets directory and check for a build script
          cd ./Assets

          if (Test-Path "build.bat") {
            Write-Host "Found build script. Running..."
            cmd.exe /c 'build.bat'
          } else {
            Write-Host "No build script found. Performing default build."
            mkdir ../dist
            Copy-Item -Path * -Destination ../dist -Recurse
          }

          Write-Host "UI build process complete."

      - name: Prepare Hexa
        run: |
          ../Teapot/node-v18.1.0-win-x64/node --trace-uncaught ../Hexa/bootstrap.js ../Hexa/hexa.json
          ../Teapot/node-v18.1.0-win-x64/node --trace-uncaught ../Hexa/hexa-node.js ../Hexa/hexa.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: greentea-assets-build-${{ github.sha }}
          path: ./Assets
